name: Host React App to S3
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "Installing dependencies"
      - run: npm install
      - run: echo "Building"
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v1
      - with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: aws s3 cp ./build/ s3://${{ secrets.S3_BUCKET }}/ --recursive --include "*" --region ${{ secrets.AWS_DEFAULT_REGION }}
      - run: echo "Deployed to S3 website"
