name: Host React App to S3
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "Installing dependencies"
      - run: npm install
      - run: echo "Building"
      - run: npm run build
      - run: echo "Installing python and awscli"
      - run: sudo apt-get install python3-setuptools
      - run: python3 -m pip install --user awscli
      - run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws s3 cp ./build/ s3://${{ secrets.S3_BUCKET }}/ --recursive --include "*"
      - run: echo "Deployed to S3 website"

